eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    enabled: true

microservices:
  user-management-service-endpoints:
    fetch-user-list-by-contact-uri: http://USER-MANAGEMENT-APP/user-management-app/operations/user-details-list/by-contact
    fetch-user-list-by-id: http://USER-MANAGEMENT-APP/user-management-app/operations/user-details-list/by-id
  
